# Generated by Django 4.2.25 on 2025-11-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=20)),
                ('fees', models.CharField(max_length=20)),
                ('courseduration', models.CharField(max_length=20)),
                ('coursedetail', models.CharField(max_length=100)),
                ('courseicon', models.FileField(upload_to='')),
            ],
        ),
    ]
